### ISSUE TITLE
any way to disable auto link generation for embedded resources?

### ISSUE THREAD

**Issue by ashic** [JakeGinnivan/WebApi.Hal#94] opened 2015-01-08 22:52 UTC
With the latest version (2.5), it appears that if you have a Representation nested in another Representation, then in the json, an entry is added to the root's _links in addition to _embedded. The link wasn't auto generated in 2.4. Since the link is available in the embedded's self link anyway, is there a way to prevent the entry in _links in the root from being generated? i.e. is it possible to revert to 2.4 behaviour?

**Comment by ashic** [comment] 2015-01-09 10:08
Ok. But let's have a look at a resource that has a list of resources (i.e. I want a list of beers). A sample response from the official beers sample is here:

https://gist.github.com/ashic/720fc08c0c6422e62b50 

If my client **doesn't** support embedded resources, what is the link to go and get the resource representing a list of beers? Or is the client supposed to do one get per link in the _links.beer array? That seems quite ridiculous to be honest...the whole reason for a list view in most cases is to provide a way of getting to an individual item. If I have to get each item to build my list, and then go to one....50 items per page, ok...let's do 51 GETs...hmmm....

What should the approach be in this case? Would it be to not make the "list item"s (i.e. Beer) a Representation, rather a POCO, and add in a normal List property of that pocos to the root resource (and an additional templated link to get to the details)? In that case, we'd have a POCO Beer to put in the list and a BeerDetailsRepresentation : Representation for the detail. Would that be the way to go?

**Comment by ashic** [comment] 2015-01-09 10:12
In addition, I'm slightly confused by the spec supporting an array of links (slightly off topic and more to do with the hal spec, but thought you might give some insight!). _links : foo : [{href='x'}, {href='y'}] seems like a blob of links without any notion of entries being linked to some data. How do we relate any of those to anything? Array index? Seems a bit dirty to be honest.

**Comment by Shazwazza** [comment] 2015-05-04 04:29
I've come up against this issue as well. It just seems like it creates more data than is necessary. Like in your beer example link, if you have 100 beers, that's an additional/duplicate of 100 href's. I was hoping that if the embedded resource URL needs to also be in the _links, then it could be templated like:

https://gist.github.com/Shazwazza/cdb64b221f8fdc568acf

I'm not sure if that makes sense with how the spec is supposed to work but seems to save a lot of duplication.

**Comment by wis3guy** [comment] 2015-05-11 12:56
To be honest i'm unsure how to respond to your comments. I feel we have correctly implemented what the specs dictate. Consider taking this up with M. Kelly as imho your comments are unrelated to WebApi.Hal, but about specifics of the HAL media type itself.

**My interpretation of the specs:**
A client, that does not support embedded resources, will need to crawl the links to (all of) these resources one by one and decide on what to display for each item and potentially in what order. I agree that it is less efficient, but that is irrelevant. As the spec states that embedded resource support is optional for clients and we want to provide a library that will yield proper HAL responses to be consumed by *any* client, we must cater for that.

HAL does not support a negotiation mechanism which allows the client to expose wether it has support for embedded resources. Only then would we be able to return optimized responses (by leaving out unneeded part). Then still, a client might want to use both parts (embedded and links) of the response.

**Comment by panmanphil** [comment] 2015-05-11 15:52
I guess I interpret the spec a little differently.  "Clients MAY be automated for this purpose so that, for any given link
   relation, they will read from an embedded resource (if present) in
   preference to traversing a link."

The text if present does seem to say it is the choice of the api author to include it or not. In the event that the resource represents an action for which there isn't a GET available, or perhaps hasn't been created yet, there is no reason to have an embedded value, correct?

In most cases though, I wonder why you wouldn't include it. The link and embedded do NOT contain the same information, except for the url which you should really think of as an opaque key to a resource. You may have a link to a person in links, but it's name and address would be in embedded. It's type is identified by the rel. The only case I can think of off the top of my head is to show a list of links.

**Comment by Shazwazza** [comment] 2015-05-11 23:10
I've ended up just leaving it the way it is in this library and now that we've got our API more or less complete, I'm very happy with the result, great lib!

At first I thought there looked to be a lot of duplication of embedded URLs since each one could be represented as a single templated URI, but that scenario would only be very specific certain data structures. And the way it is now lets HAL readers traverse the API without issue. For example, we've setup this up for a bit of testing: https://github.com/mikekelly/hal-browser  and it works perfectly and what we'd expect with the outcome of WebApi.Hal for our data.

So now that I know a bit more about this, i agree with both of your points.

**Comment by martinbooth** [comment] 2015-07-22 05:15
Am I correct in thinking this response goes against the spec?

http://haltalk.herokuapp.com/explorer/browser.html#/posts/latest

Seems like it does, yet it is from the author of the spec isn't it?

**Comment by panmanphil** [comment] 2015-07-22 13:36
Yeah, that is from the author, what to you think is incorrect about the response?

**Comment by martinbooth** [comment] 2015-07-22 13:47
Well, as per this discussion:

```Servers SHOULD NOT entirely "swap out" a link for an embedded
   resource (or vice versa) because client support for this technique is
   OPTIONAL.```

It looks like that response has a list of list of embedded posts, yet none are in the _links collection

**Comment by ashic** [comment] 2015-07-22 13:54
This is something I have issues with too. From what I understand, any resource that's embedded MUST be able to be reachable directly. i.e. if there's a resource A that's embedded in a resource B, then A must be reachable directly via it's own id (uri). It looks like the way it's generated by this framework, if a resource IS a list of things, there's no way to go to a representation of that list that isn't embedded. This only affects resources that represent a list, and my workaround is to create a "non-representation" type for the "list view". It's a pain, but it works.

**Comment by panmanphil** [comment] 2015-07-22 14:17
I see your point, yes. I think the best answer would be to browse either the HAL or api-craft mailing lists to see if this has been discussed there, or join the HAL list and ask there.

**Comment by panmanphil** [comment] 2020-10-23 00:33
closing stale issue

**Closed by panmanphil** 2020-10-23 00:33 UTC
